# Generated by Django 5.0.6 on 2024-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_l", models.BooleanField(verbose_name=True)),
                ("nombre", models.CharField(max_length=100)),
                ("editorial", models.CharField(max_length=100)),
            ],
        ),
    ]
