# Generated by Django 5.0.6 on 2024-06-01 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_libro_id_l"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="id_l",
        ),
    ]
